PersonalMvc/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PersonalMvc.Models
{
    public class Department
    {
        public int Id { get; set; }
        [Display(Name = "Отдел")]
        public string Name { get; set; }
        public ICollection<Profession> Professions { get; set; }
        public ICollection<Personal> Personals { get; set; }
        public Department()
        {
            Professions = new List<Profession>();
            Personals = new List<Personal>();
        }
    }
}

PersonalMvc/Models/Personal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PersonalMvc.Models
{
    public class Personal
    {
        public int Id { get; set; }
        [Display(Name = "ФИО")]
        public string Name { get; set; }
        public int? ProfessionId { get; set; }
        public Profession Profession { get; set; }
        public int? DepartmentId { get; set; }
        public Department Department { get; set; }
        [Display(Name = "Зарплата")]
        public int Salary { get; set; }
    }
}

PersonalMvc/Models/PersonalContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace PersonalMvc.Models
{
    public class PersonalContext:DbContext
    {
        public DbSet<Personal> Personals { get; set; }
        public DbSet<Profession> Professions { get; set; }
        public DbSet<Department> Departments { get; set; }
    }
}

PersonalMvc/Models/Profession.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PersonalMvc.Models
{
    public class Profession
    {
        public int Id { get; set; }
        [Display(Name = "Профессия")]
        public string Name { get; set; }
        public int? DepartmentId { get; set; }
        public Department Department { get; set; }
        public ICollection<Personal> Personals { get; set; }
        public Profession()
        {
            Personals = new List<Personal>();
        }
    }
}

PersonalMvc/Controllers/PersonalController.cs
using PersonalMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;

namespace PersonalMvc.Controllers
{
    public class PersonalController : Controller
    {
        PersonalContext db = new PersonalContext();
        public ActionResult Index(string searchstring, string department)
        {
            var personalList = new List<string>();
            var personalDep = from d in db.Personals orderby d.Department.Name select d.Department.Name;
            personalList.AddRange(personalDep.Distinct());
            var personals = from p in db.Personals.Include(p => p.Department).Include(p => p.Profession) select p;
            ViewBag.department = new SelectList(personalList);
            if (!string.IsNullOrEmpty(searchstring))
            {
                personals = personals.Where(p => p.Name.Contains(searchstring));
            }
            if (!string.IsNullOrEmpty(department))
            {
                personals = personals.Where(p => p.Department.Name == department);
            }
            return View(personals);
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Personal personal = db.Personals.Include(p => p.Department).Include(p => p.Profession).FirstOrDefault(p=>p.Id==id);
            if (personal == null)
            {
                return HttpNotFound();
            }
            return View(personal);
        }
        [HttpGet]
        public ActionResult ChooseDepartment()
        {
            var departments = db.Departments.ToList();
            ViewBag.Departments = departments;
            return View();
        }
        
        [HttpGet]
        public ActionResult Create()
        {
            SelectList professions = new SelectList(db.Professions, "Id", "Name");
            ViewBag.Professions = professions;
            SelectList departments = new SelectList(db.Departments, "Id", "Name");
            ViewBag.Departments = departments;
            return View();
        }
        [HttpPost]
        public ActionResult Create(Personal personal)
        {
            db.Personals.Add(personal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            SelectList professions = new SelectList(db.Professions, "Id", "Name");
            ViewBag.Professions = professions;
            SelectList departments = new SelectList(db.Departments, "Id", "Name");
            ViewBag.Departments = departments;
            Personal personal = db.Personals.Include(p => p.Profession).Include(p => p.Department).FirstOrDefault(p => p.Id == id);
            if (personal == null)
            {
                return HttpNotFound();
            }
            return View(personal);
        }
        [HttpPost]
        public ActionResult Edit(Personal personal)
        {
            db.Entry(personal).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Personal personal = db.Personals.Include(p=>p.Profession).Include(p=>p.Department).FirstOrDefault(p=>p.Id==id);
            if(personal == null)
            {
                return HttpNotFound();
            }
            return View(personal);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Personal personal = db.Personals.Find(id);
            if (personal == null)
            {
                return HttpNotFound();
            }
            db.Personals.Remove(personal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PersonalMvc/Views/Personal/Create.cshtml
@model PersonalMvc.Models.Personal

@{
    ViewBag.Title = "Create";
}

<h2>Добавить сотрудника</h2>

@using (Html.BeginForm())
{
    <p>
        @Html.LabelFor(model => model.Name)
        <br />
        @Html.EditorFor(model => model.Name)
    </p>
    <p>
        @Html.LabelFor(model => model.Salary)
        <br />
        @Html.EditorFor(model => model.Salary)
    </p>
    <p>
        @Html.LabelFor(model => model.Profession.Name)
        <br />
        @Html.DropDownListFor(model => model.ProfessionId, ViewBag.Professions as SelectList)
    </p>
    <p>
        @Html.LabelFor(model => model.Department.Name)
        <br />
        @Html.DropDownListFor(model => model.DepartmentId, ViewBag.Departments as SelectList)
    </p>
    <br />
    <input type="submit" value="Добавить" />
}
<br />
<div>
    @Html.ActionLink("На главную", "Index")
</div>

PersonalMvc/Views/Personal/Delete.cshtml
@model PersonalMvc.Models.Personal

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Delete";
}

<h2>Удаление сотрудника</h2>
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>

        <dt>@Html.DisplayNameFor(model => model.Profession.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Profession.Name)</dd>

        <dt>@Html.DisplayNameFor(model => model.Department.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Department.Name)</dd>

        <dt>@Html.DisplayNameFor(model => model.Salary)</dt>
        <dd>@Html.DisplayFor(model => model.Salary)</dd>
    </dl>
    @using(Html.BeginForm())
    {
        <input type="submit" value="Удалить" />
    }
</div>
@Html.ActionLink("Главная","Index");

PersonalMvc/Views/Personal/Details.cshtml
@model PersonalMvc.Models.Personal

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Details";
}

<h2>Информация о сотруднике</h2>

<div>
    <h4>Сотрудник</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Profession.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profession.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Главная", "Index")
</p>

PersonalMvc/Views/Personal/Edit.cshtml
@model PersonalMvc.Models.Personal
@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Edit";
}

<h2>Редактировать сотрудника</h2>
<hr />
<div>
    @using (Html.BeginForm())
    {
        <p>
            @Html.LabelFor(model => model.Name)
            <br />
            @Html.EditorFor(model => model.Name)
        </p>
        <p>
            @Html.LabelFor(model => model.Salary)
            <br />
            @Html.EditorFor(model => model.Salary)
        </p>
        <p>
            @Html.LabelFor(model => model.Profession.Name)
            <br />
            @Html.DropDownListFor(model => model.ProfessionId, ViewBag.Professions as SelectList)
        </p>
        <p>
            @Html.LabelFor(model => model.Department.Name)
            <br />
            @Html.DropDownListFor(model => model.DepartmentId, ViewBag.Departments as SelectList)
        </p>
        <input type="submit" value="Редактировать" />
    }
</div>

PersonalMvc/Views/Personal/Index.cshtml
@model IEnumerable<PersonalMvc.Models.Personal>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Index";
}

<h1>Справочник персонала</h1>
@using (Html.BeginForm("Index", "Personal", FormMethod.Get))
{
<p>
    Отдел: @Html.DropDownList("department", "Все")
    Сотрудник: @Html.TextBox("searchstring")
    <input type="submit" value="Фильтр" />
</p>
}
<div>
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Profession.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Department.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Salary)</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Profession.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Department.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Salary)</td>
                <td>
                    @Html.ActionLink("Подробнее", "Details", new { id = item.Id })
                    @Html.ActionLink("Редактировать", "Edit", new { id=item.Id})
                    @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</div>
@Html.ActionLink("Главная","Index")


PersonalMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Справочник персонала", "Index", "Personal", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Добавить сотрудника", "Create", "Personal")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>